import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { use } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden m-0 p-0">
      <head>
        {/* ✅ Razorpay script here */}
        <script
          src="https://checkout.razorpay.com/v1/checkout.js"
          async
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-slate-950 dark:text-white transition-colors duration-300 overflow-x-hidden m-0 p-0`}
      >
        <SessionWrapper>
          <Navbar />
          {children}
          <ToastContainer />
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
